Bump Shield RC and fix runtime issue
Bump the RC to rc.2
Runtime included the Shield VM which caused

Error: Runtime manifest specifies release 'shield' with version as '9.3.0-rc.1'. This conflicts with version '9.3.0-rc.2' specified in the deployment manifest.

removed old persistent_disk line